project:
  type: website

website:
  title: "Christian Bromley"
  repo-url: https://github.com/christianbromley/christianbromley.github.io
  sidebar:
    style: docked
    background: black
    search: true
    contents:
      - section: CV
        contents:
        - href: index.qmd
          text: Home
        - text: Experience
          file: experience.qmd
        - text: Skills
          file: skills.qmd
        - text: Education
          file: education.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/christian-bromley-8ab99475/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/christianbromley/christianbromley.github.io



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



