project:
  type: website

website:
  title: "Christian Bromley"
  repo-url: https://github.com/christianbromley/christianbromley.github.io
  sidebar:
    style: docked
    background: black
    search: true
    contents:
      - section: CV
        contents:
        - href: about.qmd
          text: About me
        - text: Experience
          file: experience.qmd
        - text: Skills
          file: skills.qmd
        - text: Publications and achievments
          file: publications.qmd
      - section: Blog
        contents:
        # - href: blog_building_site.qmd
        #   text: Building a website for your CV
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/christian-bromley-8ab99475/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/christianbromley/christianbromley.github.io



format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



