project:
  type: website

website:
  title: "Christian Bromley"
  repo-url: https://github.com/christianbromley/christianbromley.github.io
  sidebar:
    style: docked
    #background: black
    search: true
    contents:
      - section: CV
        contents:
        - text: Experience
          file: experience.qmd
        - text: Achievements
          file: publications.qmd
        - text: Skills
          file: skills.qmd
        - text: Education
          file: education.qmd
      - section: Blog
        contents:
        - href: blog_ismb.qmd
          text: ISMB ECCB conference musings
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/christian-bromley-8ab99475/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/christianbromley/christianbromley.github.io


execute:
  freeze: auto


format:
  html:
    theme:
      - minty
      # - brand
    css: styles.css
    toc: true



